# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20160514_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('user_remindnote', models.CharField(max_length=50)),
                ('user_adddate', models.DateField()),
                ('user_reminddate', models.DateField()),
                ('user_remindtime', models.TimeField()),
            ],
        ),
    ]
