# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='userid',
            new_name='user_id',
        ),
    ]
